### ISSUE TITLE
Migrate to setuptools

### ISSUE THREAD

**Issue by garberg** [SpriteLink/NIPAP#1397]
Migrate the NIPAP Python packages to setuptools. Unfortunately the version of setuptools shipped with Ubuntu 22.04, which the CI runners run, is antique and broken.

**Comment by plajjan** [comment]
Is there a point in sticking to ubuntu 22.04 for the runners? I guess github actions `ubuntu-latest` maps to 22.04, right? but you can easily just run stuff in a container instead

```yml
  mah-job
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: "prove I'm debian"
        run: cat /etc/debian_version
```

or is this necessary for all downstream users of nipap that the setuptools is compatible with 22.04?
